#!/bin/bash

#  ncpus - Print the number of (virtual) processors
#
#  Copyright 2009 Chuan-kai Lin
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

CPUS=`grep '^processor' /proc/cpuinfo | wc -l`

function isnumber {
    [ "$1" -eq "$1" ] 2> /dev/null
}

function limit {
    if [ "$1" -gt 0 ]
    then echo "$1"
    else echo 1
    fi
}

function offset {
    if isnumber "$1"
    then limit "$[CPUS$1]"
    else echo "$CPUS"
    fi
}

if [ -z "$1" ]
then echo "$CPUS"
elif [ "$1" != "${1##+}" ]
then offset "$1"
elif [ "$1" != "${1##-}" ]
then offset "$1"
elif isnumber "$1"
then limit "$1"
else echo "$CPUS"
fi
